################################################
# Server configurations
################################################
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080


################################################
# Application (global) configurations
################################################
application:
  # License path
  # Absolute path to GroupDocs license file
  licensePath:  C:/GroupDocs/Java/Viewer/GroupDocs.Viewer.Java.lic

################################################
# Common configurations
################################################
common:
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: true
  # Page navigation
  # Set false to disable document navigation (go to next, previous, last and first page)
  pageSelector: true
  # Document download
  # Set false to disable document download
  download: true
  # Document upload
  # Set false to disable document upload
  upload: true
  # Document print
  # Set false to disable document print
  print: true
  # File browser
  # Set false to disable document browse
  browse: true

################################################
# GroupDocs.Viewer configurations
################################################
viewer:
  # Files directory path
  # Absolute path to files directory
  filesDirectory: C:/GroupDocs/Documents/
  # Fonts path
  # Absolute path to custom fonts directory
  fontsDirectory:
  # Default document
  # Absolute path to default document
  defaultDocument:
  # HTML rendering mode
  # Set false for image mode
  # Set true for HTML mode
  htmlMode: true
  # Pages preload
  # How many pages from a document should be loaded, remaining pages will be loaded on page scrolling
  # Set 0 to load all pages at once
  preloadPageCount: 0
  # Document zoom
  # Set false to disable document zooming
  zoom: true
  # Document search
  # Set false to disable document text search
  search: true
  # Thumbnails
  # Set false to disable thumbnails
  thumbnails: true
  # Page rotation
  # Set false to disable pages rotation
  rotate: true
  # Using cache
  # Set true to enable cache
  cache: true